Use gnu C standard for Go
Fixes missing setenv which is not in C standard (only in posix):
   error: implicit declaration of function ‘setenv’;
Just test Go